# Generated by Django 4.2.19 on 2025-03-08 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
