# Generated by Django 4.2.19 on 2025-03-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='viga',
            name='nombre_viga',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viga',
            name='tipo',
            field=models.CharField(choices=[('DF', 'DF'), ('YC', 'YC')], default='DF', max_length=2),
        ),
    ]
