# Generated by Django 4.2.19 on 2025-03-02 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='api.produccion'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='viga',
            name='nombre_viga',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viga',
            name='tipo',
            field=models.CharField(choices=[('DF', 'DF'), ('YC', 'YC')], default='DF', max_length=2),
        ),
    ]
