# Generated by Django 4.2.19 on 2025-03-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orden_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='orden',
            unique_together={('numero_orden', 'fecha')},
        ),
    ]
