# Generated by Django 4.2.19 on 2025-03-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orden_produccion_alter_produccion_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='produccion',
            new_name='produccion_fecha',
        ),
    ]
