# Generated by Django 4.2.19 on 2025-03-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_produccion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
