# Generated by Django 4.2.19 on 2025-03-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_produccion_orden_produccion_fecha'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orden',
            unique_together={('produccion_fecha', 'numero_orden')},
        ),
    ]
