# Generated by Django 4.2.19 on 2025-03-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_orden_numero_orden'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orden',
            unique_together=set(),
        ),
    ]
