# Generated by Django 4.2.19 on 2025-03-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_orden_unique_together"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orden",
            constraint=models.UniqueConstraint(
                fields=("numero_orden", "fecha"), name="unique_orden_fecha"
            ),
        ),
    ]
